package(default_visibility = ["//visibility:public"])

cc_library(
    name = "image",
    hdrs = ["image.h"],
    srcs = ["image.cc"],
    deps = [
        ":stb_image",
    ],
    visibility = ["//visibility:public"],
)

cc_library(
    name = "stb_image",
    hdrs = ["stb_image.h"],
)
