package(default_visibility = ["//visibility:public"])

cc_library(
    name = "shader",
    srcs = ["shader.cc"],
    hdrs = ["shader.h"],
    deps = [
        "//glad",
        "@glm",
    ],
)

cc_library(
    name = "vertex",
    hdrs = ["vertex.h"],
    deps = [
        "@glm",
    ],
)

cc_library(
    name = "texture",
    hdrs = ["texture.h"],
)
